# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='avatar',
            field=models.ImageField(default=1, upload_to=b''),
            preserve_default=False,
        ),
    ]
