# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_autor_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
